language: r
sudo: required

# R version
r: bioc-devel

# Package caching only makes sense for the release versions.
cache: packages

# Packages from Bioconductor needed
bioc_required: true

# Be strict when checking package
warnings_are_errors: true

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"

# Packages from Github
r_github_packages:
- yihui/knitr

# Package dependencies from CRAN
r_binary_packages:
  - covr

after_success:
  - Rscript -e 'library(covr);codecov()'